version: "2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-microservice-cars
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: 1234
    ports:
      - 15672:15672
      - 5672:5672
    expose:
      - 15672
      - 5672
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27020:27017
    volumes:
      - ./mongo-volume:/data/db