server:
  port: 8080
application:
  name: Car-Api
  rabbitmq:
    queue:
      name: ${APPLICATION_RABBITMQ_QUEUE_NAME:microservice_car}
    exchange:
      name: ${APPLICATION_RABBITMQ_EXCHANGE_NAME:microservice_car_reserve_exchange}
    routing:
      key: ${APPLICATION_RABBITMQ_ROUTING_KEY:microservice_car_queue_key}
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27030/cars-api
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: 1234